image: rocker/verse:latest

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  LANG: "en_US.UTF-8"

cache:
  key: r-packages
  paths:
    - $R_LIBS_USER

stages:
  - check
  - deploy

before_script:
  - mkdir -p $R_LIBS_USER
  - >
    Rscript -e '
      if (!requireNamespace("remotes", quietly = TRUE))
        install.packages("remotes", lib = Sys.getenv("R_LIBS_USER"))
      remotes::install_deps(dependencies = TRUE, lib = Sys.getenv("R_LIBS_USER"))
    '

check:
  stage: check
  script:
    - Rscript -e 'devtools::check(error_on = "warning")'
  except:
    - tags

test:
  stage: check
  script:
    - Rscript -e 'devtools::test()'
  except:
    - tags

pages:
  stage: deploy
  script:
    - >
      Rscript -e '
        if (!requireNamespace("pkgdown", quietly = TRUE))
          install.packages("pkgdown", lib = Sys.getenv("R_LIBS_USER"))
        pkgdown::build_site(override = list(destination = "public"))
      '
  artifacts:
    paths:
      - public
  only:
    - main
    - master
